basePath: /api
definitions:
  models.ErrorHTTP:
    properties:
      errorMessage:
        type: string
      hasError:
        type: boolean
      status:
        type: string
    type: object
  models.Inscribe:
    properties:
      commit:
        type: string
      fees:
        type: integer
      inscription:
        type: string
      reveal:
        type: string
    type: object
  models.ListInscriptionsResponse:
    properties:
      hasError:
        type: boolean
      inscriptions:
        items:
          $ref: '#/definitions/models.TxTable'
        type: array
      status:
        type: string
    type: object
  models.MintRequest:
    properties:
      base64:
        type: string
      format:
        type: string
    type: object
  models.NewAddressRequest:
    properties:
      address:
        type: string
    type: object
  models.SendRequest:
    properties:
      Address:
        type: string
      InscriptionID:
        type: string
    type: object
  models.TxTable:
    properties:
      base64:
        type: string
      bc_address:
        type: string
      content_link:
        type: string
      id:
        type: integer
      link:
        type: string
      ord_id:
        type: string
      tx_id:
        type: string
    type: object
host: 89.116.25.234:7500
info:
  contact:
    email: m1chlcz18@gmail.com
    name: Michal Žídek
    url: http://app.rocketbot.pro
  description: Private API for ORD
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Rocketbot ORD API
  version: "1.0"
paths:
  /address:
    get:
      consumes:
      - application/json
      description: Mint Inscription
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.NewAddressRequest'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
      summary: Mint Inscription
      tags:
      - Daemon
  /inscriptions:
    get:
      consumes:
      - application/json
      description: List of Inscriptions in the wallet
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ListInscriptionsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
      summary: List of Inscriptions in the wallet
      tags:
      - Inscriptions
  /mint:
    post:
      consumes:
      - application/json
      description: Mint an Inscription
      parameters:
      - description: File in base64 and file type
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.MintRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Inscribe'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
      summary: Mint an Inscription
      tags:
      - Inscriptions
  /send:
    post:
      consumes:
      - application/json
      description: Send an Inscription
      parameters:
      - description: File in base64 and file type
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.SendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Inscribe'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
      summary: Send an Inscription
      tags:
      - Inscriptions
  /transactions:
    get:
      consumes:
      - application/json
      description: List of transactions in the BTC Core
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              properties:
                abandoned:
                  type: boolean
                address:
                  type: string
                amount:
                  type: number
                bip125-replaceable:
                  type: string
                blockhash:
                  type: string
                blockheight:
                  type: integer
                blockindex:
                  type: integer
                blocktime:
                  type: integer
                category:
                  type: string
                confirmations:
                  type: integer
                fee:
                  type: number
                label:
                  type: string
                parent_descs:
                  items:
                    type: string
                  type: array
                time:
                  type: integer
                timereceived:
                  type: integer
                trusted:
                  type: boolean
                txid:
                  type: string
                vout:
                  type: integer
                walletconflicts:
                  items: {}
                  type: array
                wtxid:
                  type: string
              type: object
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
      summary: List of transactions in the BTC Core
      tags:
      - Transactions
swagger: "2.0"
