basePath: /api
definitions:
  models.ErrorHTTP:
    properties:
      errorMessage:
        type: string
      hasError:
        type: boolean
      status:
        type: string
    type: object
  models.EstimateRequest:
    properties:
      blocks:
        type: integer
      imageUrl:
        type: string
    type: object
  models.FeeResponse:
    properties:
      feeRate:
        type: integer
      hasError:
        type: boolean
      status:
        type: string
    type: object
  models.HttpSuccess:
    properties:
      hasError:
        type: boolean
      message:
        type: string
    type: object
  models.Inscribe:
    properties:
      commit:
        type: string
      fees:
        type: integer
      inscription:
        type: string
      reveal:
        type: string
    type: object
  models.InscriptionPicResponse:
    properties:
      base64:
        type: string
      hasError:
        type: boolean
      status:
        type: string
    type: object
  models.ListInscriptionsResponse:
    properties:
      hasError:
        type: boolean
      inscriptions:
        items:
          $ref: '#/definitions/models.TxTable'
        type: array
      status:
        type: string
    type: object
  models.MintRequest:
    properties:
      base64:
        type: string
      feeRate:
        type: integer
      format:
        type: string
    type: object
  models.NSFWInscriptionsResponse:
    properties:
      hasError:
        type: boolean
      inscriptions:
        items:
          $ref: '#/definitions/models.NSFWTable'
        type: array
      status:
        type: string
    type: object
  models.NSFWTable:
    properties:
      approved:
        type: boolean
      bc_address:
        type: string
      content_link:
        type: string
      id:
        type: integer
      link:
        type: string
      ord_id:
        type: string
      tx_id:
        type: string
    type: object
  models.NewAddressRequest:
    properties:
      address:
        type: string
    type: object
  models.RawTransaction:
    properties:
      blockhash:
        type: string
      blocktime:
        type: integer
      confirmations:
        type: integer
      hash:
        type: string
      hex:
        type: string
      locktime:
        type: integer
      size:
        type: integer
      time:
        type: integer
      txid:
        type: string
      version:
        type: integer
      vin:
        items:
          $ref: '#/definitions/models.Vin'
        type: array
      vout:
        items:
          $ref: '#/definitions/models.Vout'
        type: array
      vsize:
        type: integer
      weight:
        type: integer
    type: object
  models.ScriptPubKey:
    properties:
      address:
        type: string
      asm:
        type: string
      desc:
        type: string
      hex:
        type: string
      type:
        type: string
    type: object
  models.ScriptSig:
    properties:
      asm:
        type: string
      hex:
        type: string
    type: object
  models.SendRequest:
    properties:
      Address:
        type: string
      InscriptionID:
        type: string
      feeRate:
        type: integer
    type: object
  models.TestPicReq:
    properties:
      base64:
        type: string
      filename:
        type: string
    type: object
  models.TestPicResponse:
    properties:
      hasError:
        type: boolean
      nsfwPicture:
        type: boolean
      nsfwText:
        type: boolean
      status:
        type: string
    type: object
  models.TxTable:
    properties:
      base64:
        type: string
      bc_address:
        type: string
      content_link:
        type: string
      id:
        type: integer
      link:
        type: string
      ord_id:
        type: string
      tx_id:
        type: string
    type: object
  models.Vin:
    properties:
      scriptSig:
        $ref: '#/definitions/models.ScriptSig'
      sequence:
        type: integer
      txid:
        type: string
      txinwitness:
        items:
          type: string
        type: array
      vout:
        type: integer
    type: object
  models.Vout:
    properties:
      "n":
        type: integer
      scriptPubKey:
        $ref: '#/definitions/models.ScriptPubKey'
      value:
        type: number
    type: object
host: 89.116.25.234:7500
info:
  contact:
    email: m1chlcz18@gmail.com
    name: Michal Žídek
    url: http://app.rocketbot.pro
  description: Private API for ORD
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Rocketbot ORD API
  version: "1.0"
paths:
  /address:
    get:
      consumes:
      - application/json
      description: Get new BTC Address
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.NewAddressRequest'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
      summary: Get new BTC Address
      tags:
      - Daemon
  /estimate:
    post:
      consumes:
      - application/json
      description: Estimate inscription cost !!!Don't use this method!!!
      parameters:
      - description: Image URL from hosting service and number of blocks
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.EstimateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Inscribe'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
      summary: Estimate inscription cost !!!Don't use this method!!!
      tags:
      - Inscriptions
  /feerate:
    get:
      consumes:
      - application/json
      description: Get fee rate for transaction
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.FeeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
      summary: Get fee rate for transaction
      tags:
      - Fees
  /inscription/image:
    get:
      consumes:
      - application/json
      description: Get Base64 image from Inscription ID
      parameters:
      - description: Inscription ID
        in: query
        name: idInscription
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.InscriptionPicResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
      summary: Get Base64 image from Inscription ID
      tags:
      - Inscriptions
  /inscriptions:
    get:
      consumes:
      - application/json
      description: List of Inscriptions in the wallet
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ListInscriptionsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
      summary: List of Inscriptions in the wallet
      tags:
      - Inscriptions
  /inscriptions/nsfw:
    get:
      consumes:
      - application/json
      description: List of Inscriptions in the wallet waiting to be approved
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.NSFWInscriptionsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
      summary: List of Inscriptions in the wallet waiting to be approved
      tags:
      - Inscriptions
  /inscriptions/nsfw/approve:
    get:
      consumes:
      - application/json
      description: Approve Inscription from NSFW list
      parameters:
      - description: ORD id
        in: query
        name: ord
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HttpSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
      summary: Approve Inscription from NSFW list
      tags:
      - Inscriptions
  /mint:
    post:
      consumes:
      - application/json
      description: Mint an Inscription
      parameters:
      - description: File in base64 and file type
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.MintRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Inscribe'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
      summary: Mint an Inscription
      tags:
      - Inscriptions
  /nsfw:
    post:
      consumes:
      - application/json
      description: Test picture for NSFW content
      parameters:
      - description: File in base64 and filename
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.TestPicReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TestPicResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
      summary: Test picture for NSFW content
      tags:
      - NSFW
  /send:
    post:
      consumes:
      - application/json
      description: Send an Inscription
      parameters:
      - description: File in base64 and file type
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.SendRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Inscribe'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
      summary: Send an Inscription
      tags:
      - Inscriptions
  /transaction/raw:
    get:
      consumes:
      - application/json
      description: Get Raw transaction from BTC code
      parameters:
      - description: Transaction ID
        in: query
        name: tx
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.RawTransaction'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
      summary: Get Raw transaction from BTC code
      tags:
      - Transactions
  /transactions:
    get:
      consumes:
      - application/json
      description: List of transactions in the BTC Core
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              properties:
                abandoned:
                  type: boolean
                address:
                  type: string
                amount:
                  type: number
                bip125-replaceable:
                  type: string
                blockhash:
                  type: string
                blockheight:
                  type: integer
                blockindex:
                  type: integer
                blocktime:
                  type: integer
                category:
                  type: string
                confirmations:
                  type: integer
                fee:
                  type: number
                label:
                  type: string
                parent_descs:
                  items:
                    type: string
                  type: array
                time:
                  type: integer
                timereceived:
                  type: integer
                trusted:
                  type: boolean
                txid:
                  type: string
                vout:
                  type: integer
                walletconflicts:
                  items: {}
                  type: array
                wtxid:
                  type: string
              type: object
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorHTTP'
      summary: List of transactions in the BTC Core
      tags:
      - Transactions
swagger: "2.0"
